
name: Trigger Backend Update

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes
  workflow_dispatch:      # Allow manual trigger

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Update (Force Refresh)
        run: |
          curl -X GET "https://vspo-proxy-git-main-renas-projects-c8ce958b.vercel.app/api/youtube?force_refresh=true&password=${{ secrets.ADMIN_PASSWORD }}"
